"""Editable slide content. Layout is implemented in tools/make_slides.py.

25 core slides + 8 optional appendix slides. Speaker notes contain timing,
questions, expected outcomes, transitions, and source references.
"""
SLIDES = [
 dict(title='Dijkstra and A*', subtitle='When can a route be finalized?',time='00-01',phase=0,kind='cover',
      notes='Open with the question of certification, not the names of data structures. Ask: finding a route is one task; how would we know no cheaper route remains? Explain that the lecture reconstructs decisions through counterexamples rather than retelling historical discovery. Prerequisites: graphs, elementary Python, asymptotic notation. Do not show the solution path yet. Pedagogical inspiration: P1, P2.'),
 dict(title='Finding a route is only half the problem.',kicker='01 / WHY SEARCH?',time='01-03',phase=0,kind='cards',
      cards=[('Navigation','A current position is not a route.\nWhat path minimizes the chosen cost?'),
             ('Networks','Which next hop and outgoing interface?\nOSPF builds shortest-path trees.'),
             ('Agents','Which sequence of valid moves?\nThe state must encode what matters.')],
      bottom='Can you certify that no cheaper route exists?',refs=['R6'],
      notes='Use Google Maps only as a familiar application, not a claim about its current implementation. Distinguish satellite positioning from road routing. For networks say next-hop router and outgoing interface, not application port. OSPF RFC 2328 section 16.1 is the documented Dijkstra example. Ask what objective each model optimizes; distance and travel time need not agree.'),
 dict(title='First, agree on the problem.',kicker='MODEL / OBJECTIVE / OUTPUT',time='03-05',phase=0,kind='formula',
      formula='minimize  C(P) = sum of edge costs on P',
      left=('Given','A finite directed graph G=(V,E).\nStart s, target t.\nFixed, nonnegative edge costs.'),
      right=('Return','The minimum cost.\nA route attaining it.\nOr: all distances from s.'),
      bottom='What should happen if t is unreachable? What if s = t?',refs=['R1','R4'],
      notes='Establish fixed additive nonnegative costs. We will later test why the sign assumption is needed. Distinguish cost, path, and all single-source distances. Expected boundary answers: unreachable gives infinity / no route; s=t gives cost zero and [s]. A target-limited run does not necessarily finalize all other labels.'),
 dict(title='A graph model is not a storage format.',kicker='FROM THE WORLD TO MEMORY',time='05-09',phase=0,kind='cards',
      cards=[('Model','Intersections, grid cells, or regions?\nChoose states and valid transitions.'),
             ('Store','Adjacency list: O(n+m).\nMatrix: O(n²) entries.'),
             ('Generate','For an implicit grid, compute\nneighbors when needed.')],
      bottom='For the live code: a dictionary of outgoing (neighbor, cost) pairs.',refs=['R4'],
      notes='Show graphs/main_graph.py with heuristic values hidden. Separate navigation meshes and geographic modeling from matrix/list storage. Mention a turn-dependent cost may require the incoming direction in the state. Avoid a survey of mesh formats. Exit at minute 9 with the objective and adjacency representation agreed.'),
 dict(title='Could we simply try every route?',kicker='02 / ENUMERATION',time='09-12',phase=1,kind='graph',image='main_graph_print.png',
      side_title='First conjecture',side='Enumerate candidate routes.\nAdd their edge costs.\nKeep the cheapest.',
      bottom='What does the cycle A → B → A do to this plan?',
      notes='Draw the main graph once on the board. Ask for the cost of S->T and any cheaper candidate. Then expose the A-B cycle. Refine unrestricted walks to simple paths. With nonnegative edge costs removing a cycle cannot worsen the route, so an optimal simple path exists whenever the goal is reachable.'),
 dict(title='Simple does not mean few.',kicker='LIVE CODE / CHECKPOINT 01',time='12-16',phase=1,kind='code',
      code='for v, weight in graph[u]:\n    if v not in on_path:\n        explore(v, cost + weight)\n\n# on_path belongs to this route.\n# It is not a global visited set.',
      side_title='Predict before running',side='How many complete routes?\nWhen would this approach\nbecome infeasible?',
      bottom='Many different routes reach the same intermediate state.',refs=['R5'],
      notes='Complete checkpoint 01 or its notebook cell. The slide is an excerpt; the checkpoint includes adding/removing nodes from on_path. Reference result: 8 simple S-to-T paths, optimum 8. Show prepared complete-graph scaling; factorial path count is not the complexity of one DFS traversal. Do not wait for unbounded enumeration. Transition: which expensive prefixes can we discard?'),
 dict(title='Which prefixes are already dominated?',kicker='03 / KEEP ONLY WHAT CAN MATTER',time='16-18',phase=2,kind='formula',
      formula='Same state B:  cost 6  versus  cost 3',
      left=('Discard','The more expensive prefix\nhas no advantage for the\nremaining state-based journey.'),
      right=('Remember','g(v): best discovered cost.\nparent(v): predecessor for\nthat improving route.'),
      bottom='Best discovered is not yet proved optimal.',refs=['R1','R4'],
      notes='Ask whether the expensive prefix can lead to a cheaper total using the same continuation. Under this state model it cannot. Clarify that a state must contain sufficient history; otherwise dominance can fail. Define tentative g and predecessors before naming relaxation. Do not call g the true shortest distance yet.'),
 dict(title='What should we process next?',kicker='RELAXATION + FRONTIER ORDER',time='18-22',phase=2,kind='graph',image='main_graph.png',
      side_title='After expanding S',side='A: 2\nB: 6\nD: 2\nT: 15\n\nChoose the smallest g.',
      bottom='candidate = g(u) + c(u,v)    ·    accept only a strict improvement',refs=['R1'],
      notes='Trace changed labels at the board. Correct non-stale order: S, A, D, B, E, C, F, G, T. B improves 6->3; C 8->4; T 15->11->8. Use neighbor order and FIFO tickets for ties. Ask whether discovering T at 15 permits stopping. Distinguish a priority based on accumulated cost from choosing the cheapest next edge.'),
 dict(title='Why is the smallest label final?',kicker='PROOF OBLIGATION',time='22-26',phase=2,kind='proof',
      steps=[('Assume','There is a cheaper route to the selected u.'),
             ('Find','Take its first unfinalized node y and predecessor x.'),
             ('Compare','Relaxation exposed y; a nonnegative suffix cannot lower cost.')],
      bottom='Minimum extraction forces  g(u) ≤ g(y) ≤ optimal cost to u.',refs=['R1','R4'],
      notes='Collaborative proof. Let S be finalized. By induction dist(x)=delta(x); optimal-prefix relaxation gives dist(y)=delta(y). Nonnegative suffix yields delta(y)<=delta(u), while minimum extraction yields dist(u)<=dist(y). Contradiction if dist(u)>delta(u). Ask which inequality needs nonnegativity. The heap does not prove the theorem; it implements the selection rule. Full proof in appendix and technical notes.'),
 dict(title='Attack the assumption, not the conclusion.',kicker='COUNTEREXAMPLE / NEGATIVE EDGE',time='26-28',phase=2,kind='graph',image='negative_graph.png',
      side_title='Predict the failure',side='Which goal cost is\nextracted first?\n\nCan a later suffix\nmake a route cheaper?',
      bottom='Which exact line of the finalization argument breaks?',refs=['R1','R4'],
      notes='S->T=2, S->B=5, B->T=-4. First target extraction costs 2; optimum via B is 1. The nonnegative-suffix inequality fails. The normal reference code rejects this input. Keep Bellman-Ford as a named alternative only. Move to implementation at minute 28.'),
 dict(title='Make the proof executable.',kicker='LIVE CODE / CHECKPOINT 02',time='28-34',phase=2,kind='code',
      code='candidate = popped_g + weight\nif candidate < dist[v]:\n    dist[v] = candidate\n    parent[v] = u\n    heappush(queue,\n             (candidate, ticket, v))',
      side_title='Three decisions',side='Accumulate route cost.\nKeep only strict improvements.\nSchedule the improved route.',
      bottom='A queue entry is a proposal about a route, not a certificate.',refs=['R2'],
      notes='Use checkpoint 02; imports and initialization are prepared. The displayed ticket is shorthand for next(ticket) in the full implementation. Fill candidate and comparison, ask for a prediction, and run. Do not live-implement heapq. Keep proof meanings aligned with variables.'),
 dict(title='What happens to the old B = 6 entry?',kicker='LAZY QUEUE / CHECKPOINT 03',time='34-38',phase=2,kind='code',
      code='popped_g, _, u = heappop(queue)\nif popped_g != dist[u]:\n    continue\n\n# B=3 superseded B=6.\n# C=4 superseded C=8.',
      side_title='Two separate records',side='Keep the new route.\nLeave the old record in the heap.\nDiscard it when it reaches the top.',
      bottom='Update parent(v) on every improvement, not just first discovery.',refs=['R2'],
      notes='Use visualizer lazy/main, next meaningful events until the first stale skip. Show the sorted queue and actual heap-array views. Main target run skips B6 and C8; later old T records remain in the queue at termination. Emphasize that an obsolete path need not be nonexistent; it has just been superseded. Finish checkpoint 03.'),
 dict(title='Stop at discovery—or at certification?',kicker='TERMINATION / CHECKPOINT 04',time='38-41',phase=2,kind='cards',
      cards=[('Discovery','A route to T exists.\nIts cost is only an upper bound.'),
             ('Extraction','After the stale guard,\nminimum-g T is certified.'),
             ('Continue','With no target stop,\nfinalize every reachable distance.')],
      bottom='Do not label every tentative distance “shortest” after an early stop.',refs=['R1'],
      notes='Demonstrate experiments.stop_on_generation_bug returning 15. The correct main graph returns 8. Place target check after rejecting stale records. Use target=None or --all to compute all reachable distances. Explain Result.finalized. In some graphs early target extraction leaves other finite labels improvable.'),
 dict(title='Can each frontier node have one entry?',kicker='EAGER QUEUE / CHECKPOINT 05',time='41-46',phase=2,kind='code',
      code='if v in queue:\n    queue.decrease_key(v, candidate)\nelse:\n    queue.insert(v, candidate)\n\n# heap array + node→position map',
      side_title='What changes?',side='The search rule does not.\nThe queue bookkeeping does.\nEvery swap repairs the map.',
      bottom='Use the prepared indexed heap; inspect one decrease-key operation.',refs=['R2','R7'],
      notes='Use the already written IndexedMinPQ and complete checkpoint 05. Do not build the heap live. Demonstrate one decrease-key event. Main graph eager uses 9 insertions, 4 decreases and peak queue 4, versus lazy 13 insertions and peak queue 6. The FIFO ticket is refreshed on improvement so variants use aligned tie policies.'),
 dict(title='Smaller queues do not prove faster runs.',kicker='COMPLEXITY / EXPLICIT GRAPH',time='46-48',phase=2,kind='complexity',
      bottom='n = |V|, m = |E|. For simple graphs, log m = O(log n).',refs=['R2','R7'],
      notes='Lazy: O(n+m log(m+1)) time and O(n+m) auxiliary memory. Eager: O((n+m)log(n+1)) time and O(n) auxiliary memory. Both exclude graph storage. Eager is not guaranteed faster; the pure-Python indexed heap and standard heapq differ in constants. Mention d-ary/Fibonacci only as an appendix extension. Protect the 54-minute A* start.'),
 dict(title='Which term in the priority mentions T?',kicker='04 / USE THE TARGET',time='48-51',phase=3,kind='graph',image='main_graph.png',
      side_title='Priority = g(v)',side='The detour is cheap so far.\nDijkstra processes it\nbefore certifying T=8.',
      bottom='Dijkstra respects edge direction. It does not use target information to prioritize.',refs=['R4'],
      notes='Point to D-E-F-G as the tempting low-cost branch. Ask students how they might avoid it without risking optimality. Use saved grid results or the notebook for the wavefront intuition; the closing application is deferred. Always compare target-stopped Dijkstra with target-stopped A*.'),
 dict(title='What if we use only the estimated distance?',kicker='A PLAUSIBLE REPAIR THAT FAILS',time='51-54',phase=3,kind='graph',image='main_graph_heuristic.png',
      side_title='Priority = h(v)',side='The goal has h(T)=0.\nIts first discovered route\ncosts 15.\n\nWhat did we forget?',
      bottom='Estimated remaining cost cannot replace accumulated route cost.',refs=['R3'],
      notes='Introduce greedy best-first search briefly as the natural suggestion, not an extra implementation project. On this graph direct T is available at h=0 and would be selected, giving cost15. Reveal the main graph coordinate-based Manhattan heuristic. Ask how to retain the useful information from Dijkstra.'),
 dict(title='Keep the past. Estimate the future.',kicker='A* / f = g + h',time='54-58',phase=3,kind='graph',image='main_graph_heuristic.png',
      side_title='Selected (g, f)',side='S: (0, 6)\nA: (2, 7)\nB: (3, 7)\nC: (4, 7)\nT: (8, 8)',
      bottom='D remains at f = 2 + 7 = 9.    Setting h = 0 recovers Dijkstra.',refs=['R3'],
      notes='Derive f=g+h before showing the trace. Four expansions exclude the goal pop. h is the exact cost of a relaxed Manhattan problem; every main-graph arc costs at least its Manhattan displacement. Coordinates are in graphs/main_graph.py. Now ask why adding any arbitrary estimate should preserve correctness.'),
 dict(title='What promise must the estimate make?',kicker='REFUTE OVERCONFIDENCE',time='58-61',phase=3,kind='formula',
      formula='0 ≤ h(v) ≤ h*(v)     and     h(T) = 0',
      left=('Break it first','Change h(A) to 20.\nCan an inflated estimate\nhide the optimal route?'),
      right=('Admissibility','Never overestimate\nthe true remaining\noptimal cost.'),
      bottom='The proof needs an appropriate optimal-prefix representative on the frontier.',refs=['R3'],
      notes='Before displaying the formal definition, run visualizer overestimate/A*. It returns11 via S-B-C-T instead of8. h*(A)=6 so20 overestimates. Give the optimal-prefix frontier argument f<=C*; a suboptimal goal has f=g>C*. Do not say every f-value is a lower bound on the global optimum. Leave duplicate handling as the next proof obligation.'),
 dict(title='Does admissibility let us close forever?',kicker='COUNTEREXAMPLE / REOPENING',time='61-66',phase=3,kind='graph',image='reopening_graph.png',
      side_title='Predict, then trace',side='A is expanded at g=3.\nB later proposes A at g=2.\n\nShould we ignore\nthat improvement?',
      bottom='All h values are admissible. Inspect the edge B → A.',refs=['R3','R4'],
      notes='Ask for the true remaining cost from B (4). A expanded at g3 discovers T6; B at f5 improves A to2. Permanently closed A yields6; reopening yields5 with one re-expansion. Use the Broken: never reopen toggle, clearly labeled. Distinguish stale records from genuinely improved states. Keep students accountable for the queue prediction.'),
 dict(title='Recover the finalization argument.',kicker='CONSISTENCY AS NONNEGATIVE REWEIGHTING',time='66-68',phase=3,kind='formula',
      formula='h(u) ≤ c(u,v) + h(v)',
      left=('Local condition','The estimate cannot drop\nby more than the cost\nof taking an edge.'),
      right=('Reweighted cost','c_h(u,v) = c(u,v)\n              + h(v) - h(u)\nConsistency means c_h ≥ 0.'),
      bottom='Along a route:  g_h(v) = f(v) - h(S).  The ordering is Dijkstra again.',refs=['R4'],
      notes='At B->A the inequality fails4>1+0; reweighted cost becomes-3. Explain the telescope and constant shift. Consistency gives the Dijkstra-like no-reopening guarantee. Under admissibility alone retain reopening. Full proof and reweighted diagram in the appendix. Do not exceed minute68.'),
 dict(title='A small code change. A new proof obligation.',kicker='LIVE CODE / CHECKPOINT 06',time='68-73',phase=3,kind='code',
      code='priority = candidate + h(v)\nheappush(queue,\n         (priority, ticket, candidate, v))\n\nf, _, queued_g, u = heappop(queue)\nif queued_g != dist[u]:\n    continue',
      side_title='Keep the distinctions',side='f chooses what comes next.\ng records the route cost.\nA better g may reopen a state.',
      bottom='Do not compare f against g in the stale-entry guard.',refs=['R2','R3'],
      notes='Complete checkpoint06, which uses the same ideas as this excerpt. Ticket is next(ticket) in the full code. Reference expanded set records statistics and never blocks improved routes. Run main, reopening, and h=0. With aligned ties, h=0 reproduces lazy Dijkstra behavior.'),
 dict(title='Which improvements did we actually obtain?',kicker='COMPARE CORRECT OUTPUTS FIRST',time='73-77',phase=4,kind='comparison',
      bottom='Goal extraction is not an expansion. These counts describe this fixture, not every graph.',
      notes='The displayed counts are generated from the reference main graph. All correct algorithms return8. A* expands4 vs8 but peak queue6 equals lazy Dijkstra here. Eager reduces peak queue to4. Brute force examines8 complete paths with a different prefix-work unit. With consistent constant-time h the explicit-graph worst-case order remains the lazy Dijkstra bound; inconsistency can require repeated expansions. Avoid claiming universal speedup.'),
 dict(title='Compare before concluding.',kicker='05 / EXPERIMENTS',time='77-86',phase=4,kind='cards',
      cards=[('Scaling','Complete graphs:\nwhen does enumeration\nexhaust the budget?'),
             ('Bookkeeping','Lazy versus eager:\ndid fewer queue records\nproduce a faster run?'),
             ('Heuristics','Same grid, different h:\nwhat changes when walls\nor movement rules change?')],
      bottom='Use the worked notebook and saved results. Measure search separately from rendering.',refs=['R7'],
      notes='This block is currently delivered using notebooks/lecture_solutions.ipynb and results/comparison.md. No separate closing-demo application is in this release. 77-79 scaling;79-83 grid zero/Euclidean/Manhattan;83-85 diagonal unit move refutes Manhattan with (0,0)->(1,1);85-86 distinguish expansions, memory and runtime. A future closing app can replace the visual form without changing these questions.'),
 dict(title='What justifies an irreversible decision?',kicker='EXIT / EXPLAIN WITHOUT THE PSEUDOCODE',time='86-90',phase=4,kind='exit',
      questions=['Why is discovering the goal not enough?',
                 'When may an expanded state be closed permanently?',
                 'Why can we skip stale entries and still reopen states?'],
      bottom='Enumerate → discard dominated prefixes → prove finalization → inform → test.',
      notes='Give students one minute to answer before summarizing. Discovery only supplies an upper bound. Nonnegative costs certify minimum-g extraction; A* needs a justified heuristic and correct duplicate handling. Consistency supports permanent closure; admissibility alone requires improvements to propagate, potentially through reopening. Stale rejection removes superseded records; reopening propagates a new better route. Return to the central question.'),
 # Optional appendix follows.
 dict(title='Appendix: the complete finalization proof',kicker='OPTIONAL / DIJKSTRA',time='Appendix',phase=2,kind='proof',
      steps=[('Induction','Every node in S has dist(x)=delta(x). Choose minimum current u outside S.'),
             ('Crossing','On an optimal route to u, let y be the first node outside S and x its predecessor. Relaxation from x gives dist(y)=delta(y).'),
             ('Contradiction','Nonnegative suffix: delta(y)≤delta(u). Minimum selection: dist(u)≤dist(y). Thus dist(u)≤delta(u), while every label is a real route cost.')],
      bottom='The heap supplies the minimum candidate; the invariant supplies correctness.',refs=['R1','R4'],
      notes='Not in the timed core. The base case is s with cost0. The equality of an optimal prefix uses the shortest-path optimal substructure. Explain unreachable states remain at infinity and are never extracted.'),
 dict(title='Appendix: the same failure in another graph',kicker='OPTIONAL / POTENTIAL REWEIGHTING',time='Appendix',phase=3,kind='graph',image='reweighted_graph.png',
      side_title='c_h = c + h(v) - h(u)',side='S → B becomes 5.\nB → A becomes -3.\n\nAll fixed-endpoint routes\nshift by one constant.',
      bottom='An inconsistent heuristic can create negative reweighted edges.',refs=['R4'],
      notes='This is the four-node reopening example with reweighted costs. Original edges remain nonnegative. The sum telescopes to original path cost plus h(t)-h(s). The f ordering agrees with reweighted Dijkstra up to h(s).'),
 dict(title='Appendix: count paths, not just vertices.',kicker='OPTIONAL / ENUMERATION',time='Appendix',phase=1,kind='pathcounts',
      bottom='For complete directed graphs: sum over k=0,...,n-2 of (n-2)! / (n-2-k)! .',refs=['R5'],
      notes='Fixed distinct source and target. Choose an ordered subset of the other n-2 nodes. The complete counts grow16,326,13700,986410 for n5,7,9,11. A classroom budget may stop before reaching the complete count; do not confuse measured partial counts with this exact combinatorial count.'),
 dict(title='Appendix: a heap is a design choice.',kicker='OPTIONAL / PRIORITY QUEUES',time='Appendix',phase=2,kind='cards',
      cards=[('Binary','O(log n) inserts,\ndecreases and extracts\nwith an indexed heap.'),
             ('d-ary','Lower height, but\nmore children to compare\non extraction.'),
             ('Fibonacci','Amortized O(1) decrease.\nO(log n) extraction.\nClassical SSSP: O(m+n log n).')],
      bottom='There is no universal graph-size threshold at which the most intricate heap wins.',refs=['R7','R8'],
      notes='Not a live implementation block. For d-ary heap height log_d n; decrease costs O(log_d n), extraction O(d log_d n). Discuss operation mix and constants. Do not equate theoretical asymptotic improvement with measured runtime superiority.'),
 dict(title='Appendix: the movement model is part of h.',kicker='OPTIONAL / RELAXATION',time='Appendix',phase=3,kind='cards',
      cards=[('Four neighbors','Unit cardinal moves.\nWithout walls:\n|dx| + |dy|.'),
             ('Eight neighbors','All moves cost 1.\nWithout walls:\nmax(|dx|, |dy|).'),
             ('Weighted moves','Use a proven lower bound\nwith the correct units\nand movement costs.')],
      bottom='A diagonally adjacent goal refutes Manhattan distance when a diagonal costs 1.',refs=['R3','R4'],
      notes='Derive Chebyshev by using diagonals for min(|dx|,|dy|) steps, then cardinal steps for the remaining difference. If diagonal costs sqrt(2), use the corresponding relaxed metric instead. For time costs, a geometric distance must be converted with a valid speed bound.'),
 dict(title='Appendix: beyond the classical bound',kicker='OPTIONAL / RESEARCH CONTEXT',time='Appendix',phase=4,kind='research',
      formula='O(m log^(2/3) n)',
      side='Duan, Mao, Mao, Shu and Yin (2025)\nDirected SSSP · real nonnegative edge weights\nDeterministic · comparison-addition model',
      bottom='A model-specific research result, not an implementation or runtime claim for this lecture.',refs=['R8'],
      notes='Optional PhD-level context. Source arXiv2504.17033v2, Breaking the Sorting Barrier for Directed Single-Source Shortest Paths. It breaks the O(m+nlogn) bound on sparse graphs in the stated model. Do not label Fibonacci Dijkstra as the unqualified current state of the art. No claim is made about every computational model or current best bound.'),
 dict(title='References / algorithmic foundations',kicker='READ FURTHER',time='Appendix',phase=4,kind='references',
      entries=[('R1','Dijkstra (1959). A Note on Two Problems in Connexion with Graphs.','ir.cwi.nl/pub/9256/9256D.pdf'),
               ('R2','Python documentation. heapq: priority queue implementation notes.','docs.python.org/3/library/heapq.html'),
               ('R3','UC Berkeley CS188. Informed Search.','inst.eecs.berkeley.edu/~cs188/textbook/search/informed.html'),
               ('R4','Stanford CS221. Search II (2023), proofs and reweighting.','stanford-cs221.github.io/spring2023-extra/modules/search/search2.pdf')],
      notes='Full clickable URLs and additional provenance are in docs/references.md. All figures, graph examples, code and exercises in this package are newly created; cited lecture figures are not redistributed.'),
 dict(title='References / applications and perspective',kicker='READ FURTHER',time='Appendix',phase=4,kind='references',
      entries=[('R5','NetworkX documentation. all_simple_paths and factorial growth.','networkx.org/documentation/stable/reference/algorithms/'),
               ('R6','Moy (1998). OSPF Version 2. RFC 2328, section 16.1.','rfc-editor.org/rfc/rfc2328.html#section-16.1'),
               ('R7','Chen et al. (2007). Priority Queues and Dijkstra’s Algorithm.','www3.cs.stonybrook.edu/~rezaul/papers/TR-07-54.pdf'),
               ('R8','Duan et al. (2025). Breaking the Sorting Barrier for Directed SSSP.','arxiv.org/abs/2504.17033v2')],
      notes='Pedagogical inspiration: Toeplitz, The Calculus: A Genetic Approach (University of Chicago Press); Lakatos, Proofs and Refutations (Cambridge,1976). P1 and P2, including links, are in docs/references.md. This lecture reconstructs motivations and proof obligations; it does not purport to reenact the algorithms’ history.'),
]
